app:
  name: KnowLedger
  dev: true

log:
  level: debug
  output:
    - stderr
    - app.log

http:
  listen_addr: "0.0.0.0:3000"

database:
  dsn: "host=localhost user=user password=your_password dbname=your_db_name port=5432 sslmode=disable timezone=Asia/Jakarta"

storage:
  r2:
    bucket_name: "[BUCKET_NAME]"
    access_key: "[BUCKET_ACCESS_KEY]"
    secret_key: "[BUCKET_SECRET_ACCESS_KEY]"
    api_endpoint: "[R2_API_ENDPOINT]"
    public_endpoint: "[R2_PUBLIC_ENDPOINT/DOMAIN]"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

worker:
  pool_size: 1000

gc:
  interval_seconds: 60

admin:
  username: "admin"
  password: "admin54321"
